# Generated by Django 5.2.5 on 2025-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
    ]
