# Generated by Django 5.2.5 on 2025-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0002_alter_tenant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'payment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'order_number')},
        ),
    ]
